apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: serviceregistry-hpa 
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: serviceregistry 
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 90 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceregistry
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: serviceregistry
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: serviceregistry
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
        prometheus.io/path: /actuator/prometheus
    spec:
      containers:
      - name: serviceregistry
        image:  {{ .Values.image.name }}:{{ .Values.image.tag }} 
        envFrom:
        - configMapRef:
            name: serviceregistry
        resources:
          limits:
            cpu: "0.5"
          requests:
            cpu: "0.5"    

---
apiVersion: v1
kind: Service
metadata:
  name: serviceregistry
  labels:
    app.kubernetes.io/name: serviceregistry
spec:
  ports:
  - port: 8761
    targetPort: 8761
  selector:
    app.kubernetes.io/name: serviceregistry
